### ISSUE TITLE
Additional Security for communication

### ISSUE THREAD

**Issue by sasl83** [admin-ch/CovidCertificate-Apidoc#10]
You do not specify how the communication between a "authorized User" (Client) and the backend happens. IP or DNS? Secure the communication of the channels with aditional DNS stuff on both sides! NO direct IP access, Clients need to use DNS . Use all the power of DNS to really make sure communication is secure (DNSSEC/CAA/CERT/HSTS/etc...)! This makes the "authorized User" (Client) and the backend much more trusty.
Note: You cant use Windows-DNS for this, use BIND on Linux.

**Comment by delixfe** [comment]
@sasl83 Are you referring to the following statement?

> 3. The authorized user must insert the one-time password in the primary system so that it is transmitted when calling the REST API.

**Comment by sasl83** [comment]
Hmmm you open the source and the specs but not open for other ideas as they are in the specs or refuse to implement more security as possibel. Thats a joke
