### ISSUE TITLE
English support

### ISSUE THREAD

**Issue by ErMejo74** [admin-ch/CovidCertificate-Apidoc#15]
https://github.com/admin-ch/CovidCertificate-Apidoc#configuration-data

It would be a good idea to support English as a language.
I can easily imagine that the test results from an airport lab will generate documents in English.

**Comment by delixfe** [comment]
The certificates have always two languages: The selected one and English.
We will update the documentation.

**Comment by delixfe** [comment]
Updated documentation in 26c00deb5b766439601c8f810ece215915931b22.
