### ISSUE TITLE
Incorrect ISO Language Codes

### ISSUE THREAD

**Issue by ErMejo74** [admin-ch/CovidCertificate-Apidoc#16]
The current [section](https://github.com/admin-ch/CovidCertificate-Apidoc#configuration-data) about ISO 639-1 two-letter codes is wrong.
It lists as possible values:
    "DE"
    "FR"
    "IT"
    "RM"

ISO 639-1 are lower case two-letter codes. The list should be:
    "de"
    "fr"
    "it"
    "rm"

**Comment by delixfe** [comment]
@ErMejo74: Thank you. Fixed in 26c00deb5b766439601c8f810ece215915931b22.
